require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'FixFast' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-image-base64', :path => '../node_modules/react-native-image-base64'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  target 'FixFastTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end